apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: ngrok-vault-access
  namespace: ngrok-ingress
spec:
  appName: ngrok-home-lab
  destination:
    create: true
    labels:
      hvs: "true"
    name: ngrok-access-secret
  refreshAfter: 24h