apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: ngrok-access-secret
  namespace: ingress
spec:
  appName: home-lab
  destination:
    create: true
    labels:
      hvs: "true"
    name: ngrok-access-secret
  refreshAfter: 24h