apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: ngrok-access-secret
  namespace: vault-secrets-operator-system
spec:
  appName: ngrok-home-lab
  destination:
    create: true
    labels:
      hvs: "true"
    name: ngrok-access-secret
    namespace: ingress
  refreshAfter: 24h