apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ngrok-ingress-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: components
  source:
    repoURL: https://ngrok.github.io/kubernetes-ingress-controller
    targetRevision: "*"
    chart: kubernetes-ingress-controller
    helm: 
      releaseName: ngrok-ingress-controller
      values: |
        credentials:
          secret:
            name: "ngrok-access-secret" # set this to the secret for hashicorp vault hcp vault secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: ngrok-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true    
