apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPAuth
metadata:
  name: default
  namespace: ingress
spec:
  organizationID: "a2ca1143-511a-435c-9c2a-2d0ee2d3bb34"
  projectID: "ff6aae5e-b7f0-4ca4-a9b5-a3fabb71a864"
  servicePrincipal:
    secretRef: vso-demo-sp