apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lb-test-app
  namespace: lbtest
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tenants
  source:
    repoURL: https://github.com/rpassmore/gitops-cicd.git
    targetRevision: "*"
    path: cluster-home-lab/tenants/lb-test-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true    