apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 4.3.*
    chart: argo/argo-cd  # Set this when pulling directly from a Helm repo. DO NOT set for git-hosted Helm charts.
    helm: 
      releaseName: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true    
