apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Manages the monitoring components of the cluster via prom-grafana stack"
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # - 'https://github.com/rpassmore/grafana-dashboards-kubernetes'
  # Allow applications to deploy any namespace in the same cluster
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
