apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicorp-vault-secrets-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: components
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: "0.4.2"
    chart: vault-secrets-operator
    helm: 
      releaseName: vault-secrets-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-secrets-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
