apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: components
  source:
    repoURL: https://metallb.github.io/metallb
    targetRevision: "0.13.*"
    chart: metallb
    helm: 
      releaseName: metallb
      # values: |
      #   configInline:
      #     address-pools:
      #       - name: default
      #         protocol: layer2
      #         addresses:
      #          - 192.168.1.220/24
    # directory:
    #   recurse: true
    #   include: "metallb-config.yaml"  
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true    
