k8sServiceHost: localhost
k8sServicePort: 7445

kubeProxyReplacement: true

# Roll out cilium agent pods automatically when ConfigMap is updated.
rollOutCiliumPods: true

# Increase rate limit when doing L2 announcements
k8sClientRateLimit:
  qps: 50
  burst: 100

# Announce IPs from services' `.status.loadbalancer.ingress` field (automatically assigned by LB-IPAM).
l2announcements:
  enabled: true

# Announce manually assigned IPs from services' `.spec.externalIPs` field
externalIPs:
  enabled: true

operator:
  # Can't have more replicas than nodes
  replicas: 1

ipam:
  moode: kubernetes

securityContext:
  capabilities:
    cleanCiliumState: ["NET_ADMIN", "SYS_ADMIN", "SYS_RESOURCE"]
    ciliumAgent: ["CHOWN", "KILL", "NET", "NET_ADMIN", "NET_RAW", "IPC_LOCK", "SYS_ADMIN", "SYS_RESOURCE", "DAC_OVERRIDE", "FOWNER", "SETGID", "SETUID"]

cgroup:
  autoMount:
    enabled: false  
  hostRoot: /sys/fs/cgroup

hubble:
  enabled: true
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true

  # From the talos dockumentaion, translated fro helm cli settings 
  # --set ipam.mode=kubernetes \
  #  --set=kubeProxyReplacement=true \
  #  --set=securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}" \
  #  --set=securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}" \
  #  --set=cgroup.autoMount.enabled=false \
  #  --set=cgroup.hostRoot=/sys/fs/cgroup \
  #  --set=k8sServiceHost=localhost \
  #  --set=k8sServicePort=7445